### ISSUE TITLE
Ensure understanding of existing codebase

### ISSUE THREAD

**Issue by Cloud9-Sec** [cs481-ekh/s22-hospsim#5] opened 2022-02-10 22:31 UTC
Each team member is required to be able to understand the inherited code and be able to compile and execute the code locally.

- [x] Jonathan
- [x] Andrew
- [x] Derek
- [x] Chinwe

**Comment by AndrewGerberBSU** [comment] 2022-02-15 17:56
Did not mean to close. Will be closing #9 as it is a dupe of this one

**Comment by AndrewGerberBSU** [comment] 2022-02-15 17:56
I am really bad with buttons

**Comment by snakeround** [comment] 2022-02-15 23:13
Complete

**Closed as completed** 2022-02-17 22:47 UTC
Labels: Documentation
